Edit css files
GSG-CF05/Team10-League-of-Legends pull request #55
Opened 2022-03-22 11:42 UTC by htahrawi

2022-03-22 11:44 UTC, MzSalout approved these changes, later dismissed

2022-03-22 11:53 UTC, Bakeza approved these changes, later dismissed

2022-03-22 11:59 UTC, MzSalout submitted a review, later dismissed

2022-03-22 12:13 UTC, mohmmed23 approved these changes, later dismissed

2022-03-22 12:42 UTC, Yousef-Dall approved these changes, later dismissed

2022-03-22 12:42 UTC, Yousef-Dall commented on SkinsPage/css/media.css
> +  }
use vh not px

2022-03-22 12:42 UTC, Yousef-Dall commented on SkinsPage/css/media.css
> +    height: 450px !important;
use vh not px

2022-03-22 17:20 UTC, Bakeza approved these changes

2022-03-22 19:07 UTC, mohmmed23 approved these changes

2022-03-23 10:04 UTC, MzSalout approved these changes

2022-03-23 15:50 UTC, Yousef-Dall requested changes
edit the button style and position (in all screen sizes) to fit the one in the details page

2022-03-24 12:20 UTC, closed without merging